// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEsYpWBBbVOCUY9uvyFFeBak-Ra7DSsBo',
    appId: '1:729215882024:web:1df664d2cd2a29f568361d',
    messagingSenderId: '729215882024',
    projectId: 'fir-for-ecomerce',
    authDomain: 'fir-for-ecomerce.firebaseapp.com',
    storageBucket: 'fir-for-ecomerce.appspot.com',
    measurementId: 'G-JF8HMDS24H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7OIKRpzUf-Av5MGwIXwKrflIphwehAAI',
    appId: '1:729215882024:android:65286399d9cfab6468361d',
    messagingSenderId: '729215882024',
    projectId: 'fir-for-ecomerce',
    storageBucket: 'fir-for-ecomerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFO6Ucf5G6W70DXj9lEnOzLUJYjaRwBXs',
    appId: '1:729215882024:ios:cd6684959fbf2f8868361d',
    messagingSenderId: '729215882024',
    projectId: 'fir-for-ecomerce',
    storageBucket: 'fir-for-ecomerce.appspot.com',
    iosBundleId: 'com.example.ecomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFO6Ucf5G6W70DXj9lEnOzLUJYjaRwBXs',
    appId: '1:729215882024:ios:5f760239a13c66da68361d',
    messagingSenderId: '729215882024',
    projectId: 'fir-for-ecomerce',
    storageBucket: 'fir-for-ecomerce.appspot.com',
    iosBundleId: 'com.example.ecomerceApp.RunnerTests',
  );
}
